sudo: false
language: node_js
node_js:
    - "5.6.0"
notifications:
  email: false
before_install:
    - export TZ=America/Los_Angeles
script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
